apiVersion: apps/v1
kind: Deployment
metadata:
  name: subjugate-deployment
  labels:
    app: subjugate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subjugate
  template:
    metadata:
      labels:
        app: subjugate
    spec:
      containers:
      - name: subjugate
        image: subjugate:1.0
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_URL
          valueFrom:
            secretKeyRef:
              name: subjugate-secrets
              key: mongoDbUrl
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: subjugate-secrets
              key: redisUrl
---
apiVersion: v1
kind: Service
metadata:
  name: subjugate-service
spec:
  selector:
    app: subjugate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: subjugate-secrets
type: Opaque
data:
  mongoDbUrl: <Your MongoDB URL encoded in base64>
  redisUrl: <Your Redis URL encoded in base64>